<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'{class}\' must extend from \'yii\\rbac\\Rule\' or its child class' => '\'{class}\' musi dziedziczyć z \'yii\\rbac\\Rule\' lub jej klas potomnych',
    'Action' => 'Akcja',
    'Are you sure to delete this item?' => 'Jesteś pewien że chesz usunąć ten element?',
    'Assign' => 'Przydziel',
    'Assignment : {0}' => 'Rola : {0}',
    'Assignments' => 'Przypisz role',
    'Class Name' => 'Nazwa klasy',
    'Create' => 'Stwórz',
    'Create Rule' => 'Stwórz zasadę',
    'Create Role' => 'Stwórz rolę',
    'Data' => 'Data',
    'Delete' => 'Usuń',
    'Description' => 'Opis',
    'Invalid rule "{value}"' => 'Nieprawidłowa zasada "{value}"',
    'Item has been removed.' => 'Rekord został usunięty.',
    'Item has been saved.' => 'Rekord został zapisany.',
    'Name' => 'Nazwa',
    'Permissions' => 'Uprawnienia',
    'Refresh' => 'Odśwież',
    'Remove' => 'Usuń',
    'Roles' => 'Role',
    'Role : {0}' => 'Rola : {0}',
    'Permission : {0}' => 'Uprawnienia : {0}',
    'Create Permission' => 'Nowe uprawnienie',
    'Routes' => 'Ścieżki',
    'Rule' => 'Zasada',
    'Rule "{value}" does not exists' => 'Zasada "{value}" nie istnieje',
    'Rule : {0}' => 'Zasada : {0}',
    'Rule Name' => 'Nazwa zasady',
    'Rule has been deleted.' => 'Zasada została usunięta.',
    'Rule has been saved.' => 'Zasada została zapisana.',
    'Rules' => 'Zasady',
    'Search for assigned' => 'Wyszukaj przypisane',
    'Search for available' => 'Wyszukaj dostępne',
    'The requested page does not exist.' => 'Żądana strona nie istnieje',
    'Type' => 'Rodzaj',
    'Unknown class \'{class}\'' => 'Nieznana klasa \'{class}\'',
    'Update' => 'Aktualizuj',
    'Update Rule : {0}' => 'Aktualizuj zasadę : {0}',
    'Update Role : {0}' => 'Aktualizuj rolę : {0}',
    'Update Permission : {0}' => 'Aktualizuj uprawnienia : {0}',
    'Select Rule' => 'Wybież zasadę',
];
